# Generated by Django 3.1.7 on 2021-03-31 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_employeemodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
